export const Texts = {
    aboutHeadline: "About",
    aboutBody: `Hello, I'm Omotola. A passionate React Native Mobile App Developer with a focus  on building seamless, user-centric cross-platform applications.\nOver the years, I’ve specialized in developing performant mobile apps using React Native, Expo CLI, Redux Toolkit, JavaScript/TypeScript, Tailwind CSS, Firebase, and Git. I apply clean architecture principles and efficient testing strategies to ensure scalable and maintainable codebases.  \n\nRecently, I’ve expanded my skillset into backend development using C# and the .NET Framework, enabling me to build secure, scalable RESTful APIs that power modern mobile and web applications. I'm particularly interested in designing robust system architectures and integrating backend services that enhance performance, security, and long-term maintainability.  \nI'm a proactive learner who thrives in collaborative, fast-paced environments. Whether working independently or in a team, I’m always driven to create impactful solutions.  \n\nLet’s connect and explore opportunities to build impactful mobile apps, secure & scalable backend systems, or both.`,
    skillsHeadline: "Skills",
    skillsBodyfrontend: `React Native (Expo ), JavaScript / TypeScript, Redux Toolkit & Context API, Tailwind CSS / NativeWind, React Native Stylesheet, Firebase (Auth, Firestore, Storage), RESTful API Integration, Git & GitHub\n`,
    skillsBodybackend: `C# & .NET (Web API, Entity Framework), SQL Server, JWT Authentication, Role-Based Authorization, API Security & Middleware, Postman / Swagger UI (API Testing), Clean Architecture Principles, Agile Workflow\n`,
    skillsBodySoftskills: `Strong Communication and Collaboration, Dedication and Resilience, Problem Solving `,
    contactHeadline: "Contacts",
    contactBody: ` I'm currently open to freelance opportunities, full-time roles, or collaborative projects where I can contribute to building user-focused, performant mobile and web applications. Whether you have a question, an idea, or just want to say hello feel free to reach out. I’ll do my best to respond promptly.`,
    contactAdress:`\n📧 omotolaodumosu04@gmail.com\nLinkedIn: Omotola Odumosu\nTwitter: @YhoungBrown`
};